config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: "tasks#index"

  get 'tasks/new', to: "tasks#new"
  post 'tasks', to: "tasks#create"

  get 'tasks/:id', to: "tasks#show", as: :task

  get 'tasks/:id/edit', to: "tasks#edit", as: :edit_path
  patch 'tasks/:id', to: "tasks#update", as: :update

  delete 'tasks/:id', to: "tasks#destroy",as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @tasks = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])

  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Update <%= @task.title %></h1>


<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>Task List</h1>


<% @tasks.each do |task| %>
  <h2><input type="checkbox"><%= link_to task.title, task_path(task) %><br></h2>
  <%= link_to "Delete", task_path(task['id']),
      method: :delete,
      data: { confirm: "Are you sure?" } %>

<% end %>



  <h2><%= link_to "Create new task", tasks_new_path %></h2>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>

<form action="/tasks" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="title">Name of the task: </label>
  <input type="text" name="task[title]" id="title">

  <label for="details">Details: </label>
  <input type="text" name="task[details]" id="details">

  <input type="submit">
</form>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.details %></p>



  <p><%= link_to "Edit task", edit_path_path %><p>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>


<h1>Update</h1>

<!-- <form action="/tasks" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="title">Name of the task: </label>
  <input type="text" name="task[title]" id="title">

  <label for="details">Details: </label>
  <input type="text" name="task[details]" id="details">

  <input type="submit">
</form>
 -->